# Generated by Django 4.1.3 on 2022-11-30 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("application", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_id",
                    models.CharField(max_length=32, verbose_name="Action ID"),
                ),
                (
                    "action_name",
                    models.CharField(max_length=32, verbose_name="Action Name"),
                ),
                (
                    "resource_name",
                    models.CharField(max_length=32, verbose_name="Resource Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "application",
                    core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.application",
                        verbose_name="Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action",
                "verbose_name_plural": "Action",
                "ordering": ["-id"],
                "unique_together": {("application", "action_id")},
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instances",
                    models.JSONField(default=list, null=True, verbose_name="Instances"),
                ),
                (
                    "all_instances",
                    models.BooleanField(default=False, verbose_name="All Instances"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("denied", "denied"),
                            ("allowed", "allowed"),
                            ("dealing", "dealing"),
                        ],
                        default="dealing",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "action",
                    core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iam.action",
                        verbose_name="Action",
                    ),
                ),
                (
                    "user",
                    core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Permission",
                "verbose_name_plural": "User Permission",
                "ordering": ["-id"],
                "unique_together": {("user", "action")},
                "index_together": {("user", "action", "status")},
            },
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_id",
                    models.CharField(max_length=32, verbose_name="Instance ID"),
                ),
                (
                    "instance_name",
                    models.CharField(max_length=32, verbose_name="Instance Name"),
                ),
                (
                    "action",
                    core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iam.action",
                        verbose_name="Action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resource",
                "ordering": ["-id"],
                "unique_together": {("action", "instance_id")},
            },
        ),
    ]
