# Generated by Django 4.1.3 on 2022-12-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="resource_name",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="Resource Name"),
        ),
    ]
