# Generated by Django 4.1.3 on 2022-12-13 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models
import core.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iam", "0002_alter_action_resource_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpermission",
            name="status",
            field=models.CharField(
                choices=[
                    ("denied", "denied"),
                    ("allowed", "allowed"),
                    ("dealing", "dealing"),
                ],
                db_index=True,
                default="dealing",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="UserPermissionSnapshot",
            fields=[
                (
                    "id",
                    core.models.UniqIDField(
                        default=core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instances",
                    models.JSONField(default=list, null=True, verbose_name="Instances"),
                ),
                (
                    "all_instances",
                    models.BooleanField(default=False, verbose_name="All Instances"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("denied", "denied"),
                            ("allowed", "allowed"),
                            ("dealing", "dealing"),
                        ],
                        db_index=True,
                        default="dealing",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update At"),
                ),
                (
                    "action",
                    core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iam.action",
                        verbose_name="Action",
                    ),
                ),
                (
                    "user",
                    core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Permission Snapshot",
                "verbose_name_plural": "User Permission Snapshot",
                "ordering": ["action", "-update_at"],
                "unique_together": {("user", "action")},
                "index_together": {("user", "action", "status")},
            },
        ),
    ]
