# Generated by Django 4.1.3 on 2022-12-02 16:07

from django.db import migrations, models

import core.models
import core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoticeLog",
            fields=[
                (
                    "id",
                    core.models.UniqIDField(
                        default=core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receivers", models.JSONField(verbose_name="Receivers")),
                ("content", models.JSONField(verbose_name="Content")),
                (
                    "extra_params",
                    models.JSONField(default=dict, null=True, verbose_name="Extra Params"),
                ),
                (
                    "result",
                    models.TextField(blank=True, null=True, verbose_name="Result"),
                ),
                (
                    "send_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Send At"),
                ),
            ],
            options={
                "verbose_name": "Notice Log",
                "verbose_name_plural": "Notice Log",
                "ordering": ["-send_at"],
            },
        ),
    ]
