# Char Length
SMS_CHAR_LENGTH = 12
SHORT_CHAR_LENGTH = 32
MEDIUM_CHAR_LENGTH = 64
MAX_CHAR_LENGTH = 255
PHONE_NUMBER_CHAR_LENGTH = 11
VERIFY_CODE_LENGTH = 6

# Pagination
DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100

# Cache
DEFAULT_CACHE_TIMEOUT = 60
