# Generated by Django 4.1.3 on 2022-12-05 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coslog",
            name="upload_by",
            field=core.models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Upload By",
            ),
        ),
    ]
