# Generated by Django 4.1.3 on 2022-12-05 17:58

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userproperty",
            options={
                "ordering": ["user", "property_key"],
                "verbose_name": "User Property",
                "verbose_name_plural": "User Property",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "already in use"},
                max_length=32,
                primary_key=True,
                serialize=False,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
